### PR TITLE
[FEATURE] Implemented "bake" feature

### PR DESCRIPTION
**Pull request by kraftb**
This feature allows to keep the oven at a constant temperature for
a defined time. This can get used to "bake" Fimo, ceramics or to
incubate cell cultures, etc.

### CODE REVIEW

**Comment by kraftb** [comment]
Hi !

I created a new menu option for the ControLeo2 device. The new "baking" mode allows to keep the oven at a constant temperature for a time up to 2 hours. This can get used to bake ceramics, "fimo" or to incubate cell cultures at 35° C. Until now I did only test it for baking Fimo at 110°C. I implemented a P regulator instead of the homebrewn regulation logic. Currently it lacks an "I" regulation to become a PI regulator so it will never reach the defined target temperature but stay a few degrees below target temperature.

**Comment by kraftb** [comment]
https://en.wikipedia.org/wiki/PID_controller

**Comment by amar-s** [comment]
Thank you. I was going to suggest this feature, for drying PCB's and components. However to meet the higher levels of J-STD-033B.1, bakeout times to be able to go up to 96 hours. Specifically, I want to bake some PCB's with large BGA's prior to rework, to thoroughly dry them to prevent "popcorning". And I frequently dry other things in a small oven as well (including plastics), but often need much tighter temperature control than the oven's original controller provides. Looking forward to tinkering with this.

**Comment by kraftb** [comment]
Hi,

I do not really recall if I implemented the "I" feature but remember it is no full PID regulator. Depending of which parts of a PID regulator you implement the target temperature will never be reached exactly, or the temperature will "overshoot" the desired target temperature during heatup, etc. So depending on which regulatory arithmetic you implement you can define the heat-up.

Of course it would be possible to let the controller "learn" the characteristics of the oven, similar to the algorithm for the default JEDEC soldering. If all parameters (multiplicative constants) for the various P-I-D elements can get determined it would be possible to keep the temperature very tight to a desired temperature profile without having to learn each different temperature curve.

Allowing to select hours instead of minutes for the baking process should be quite an easy task ...

**Comment by engineertype** [comment]
The current v2.0 ControLeo2 firmware support "PI" of PID in bake mode.  It supports bake duration up to 18 hours.

**Pull request closed without merging**
